---
title: "Welcome to RNIR!"
output: md_document
sidebar: mydoc_sidebar
permalink: index.html
toc: false
---

<br>

RNIR is a series of tutorials on [chemometrics](https://en.wikipedia.org/wiki/Chemometrics) and near-infrared (NIR) data analysis with [R](https://www.r-project.org/) and [RStudio](https://www.rstudio.com/). R and RStudio are both free and open source. 

All the data used in the tutorials can be downloaded from RNIR's [GitHub](https://github.com/guifh/RNIR) repository. This ensures that any given example can be easily reproduced.  

We will start by presenting the most common methods employed in NIR spectroscopy for processing NIR spectra and developing prediction models. However, in the future, RNIR will aim at presenting more advanced spectra processing and analysis methods that can be found in the literature, but that are not yet available in R as functions or packages. RNIR will also propose tutorials on the analysis of NIR data in the fields of NIR time-resolved spectroscopy and hyperspectral imaging. 

RNIR is written in [Rmarkdown](http://rmarkdown.rstudio.com/lesson-1.html), a plain text formatting syntax designed so that it can be directly converted to HTML. This means it is easy to contribute to RNIR. If you are using R in your NIR research and would like to add your own tutorials on RNIR, feel free to contact me. Any question, comment or suggestion concerning RNIR is also appreciated.

The ultimate goal of RNIR is to facilitate the diffusion of algorithms and chemometric methods used for NIR data analysis by providing direct access to code and reproducible examples.



<br>

Thanks for reading!

<br>

**_Guillaume Hans_**

*November 12*<sup>th</sup>*, 2018* 

<br>
